# Config for OpenAI schema formatting.

task: sft
dataset_path: Alignment-Lab-AI/Lawyer-Instruct
split: train
output_dir: ""
output_name: lawyer_test_dataset
system_col: null
system_msg: "You are a helpful assistant."
user_col: "['instruction']"

# response for SFT and constitutional
response_col: "['output']"      
# for DPO
chosen_col: null
rejected_col: null
chosen_score_col: null
rejected_score_col: null
# for constitutional
critique_col: null
revised_response_col: null
